### PR TITLE
Fix/patient falling over no vital signs

### LINKED ISSUE #17: Visiting a patient more than once causes the vitals form to fall over

### PR DESCRIPTION
**Pull request by hjfitz**
resolves #17

### CODE REVIEW

File: src/client/spa/partial/vital-signs.jsx [hunk 1]
```diff
@@ -13,13 +13,13 @@ class Vitals extends Component {
 	componentDidMount() {
 		const tabs = document.querySelectorAll('.tabs')
```
Comment (SamStenton) [inline src/client/spa/partial/vital-signs.jsx:14]: eww one-time variables

File: src/server/fhir/classes/Patient.js [hunk 2]
```diff
@@ -99,11 +99,17 @@ class Patient {
...
+	 * fetch patient photo URL so that this can be removed from the disk
+	 * delete the patient from the database, then the image
+	 * order is important, because if database delete fails, no more image for patient
 	 * @returns {boolean} Deleted or nah
 	 */
 	async delete() {
 		try {
-			await knex('patient').delete('patient', this.id)
+			// get patient image url from db
+			const [row] = await knex('patient').select().where('patient', this.id)
```
Comment (SamStenton) [inline src/server/fhir/classes/Patient.js]: spicy

File: src/client/spa/pages/patient.jsx [hunk 3]
```diff
@@ -89,6 +89,7 @@ class Patient extends Component {
 
 		const patientInfo = normalisePatientInfo({...data[0].subject, ...data[0].location[0]})
 		const patientReports = normalisePatientReports(patientReport) // comes pre-sorted from API
+		console.log(patientReports)
```
Comment (SamStenton) [inline src/client/spa/pages/patient.jsx]: no logging in prod please

**Review by SamStenton — APPROVED** [review]

**Comment by SamStenton** [comment]
hope the patient is okay
